/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 3PTECh
 */
import java.awt.Color;
import java.awt.Window;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class mainLogin extends javax.swing.JFrame {

    /**
     * Creates new form mainLogin
     */
    public mainLogin() {
        initComponents();
        jPanel3.setBackground(new Color(100,0,0,30));
     //   jPanel4.setBackground(new Color(90,0,0,30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTloginUserN = new javax.swing.JTextField();
        jPloginUserN = new javax.swing.JPasswordField();
        jBloginButin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        regisRoleEslectAdmin = new javax.swing.JComboBox<>();
        registerSelctAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("LOGIN");
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("EMAIL");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 98, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("PASSWORD");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 146, -1, 20));

        jTloginUserN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTloginUserNActionPerformed(evt);
            }
        });
        jPanel3.add(jTloginUserN, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 95, 152, -1));
        jPanel3.add(jPloginUserN, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 143, 152, -1));

        jBloginButin.setBackground(new java.awt.Color(0, 153, 0));
        jBloginButin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBloginButin.setForeground(new java.awt.Color(102, 255, 255));
        jBloginButin.setText("LOGIN");
        jBloginButin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBloginButinActionPerformed(evt);
            }
        });
        jPanel3.add(jBloginButin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 396, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(153, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("REGISTER");

        regisRoleEslectAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regisRoleEslectAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STUDENT", "TEACHER", " " }));
        regisRoleEslectAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisRoleEslectAdminActionPerformed(evt);
            }
        });

        registerSelctAdmin.setBackground(new java.awt.Color(0, 153, 0));
        registerSelctAdmin.setText("OK");
        registerSelctAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerSelctAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerSelctAdmin)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(regisRoleEslectAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(regisRoleEslectAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerSelctAdmin)
                .addGap(172, 172, 172))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 123));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 380, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\3PTECh\\Documents\\NetBeansProjects\\elarning\\src\\main\\java\\icons\\pexels-tirachard-kumtanom-112571-733852.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
               
   
    private void jBloginButinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBloginButinActionPerformed

          // Get the email and password from the form fields
    String email = jTloginUserN.getText().trim(); // assuming jTloginUserN is the text field for email
    String password = new String(jPloginUserN.getPassword()); // assuming jPloginUserN is the password field

    // Validate input
    if (email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both email and password.", "Input Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

   try (Connection conn = DatabaseUtil.getConnection(); 
         PreparedStatement stmt = conn.prepareStatement("SELECT user_id, password, role FROM users WHERE email = ?")) {
        
        stmt.setString(1, email);

        try (ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                // User exists, retrieve stored password
                String storedPassword = rs.getString("password");

                // Compare the entered password with the stored password
                if (password.equals(storedPassword)) {
                    // Password matches, login successful
                    JOptionPane.showMessageDialog(null, "Login successful", "Login", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    // Retrieve user_id and role
                    int userId = rs.getInt("user_id");
                    String role = rs.getString("role");

                    // Save user_id to GlobalUserStore
                    GlobalUserStore.setUserId(userId);

                    // Open the appropriate dashboard based on the user's role
                    if ("TEACHER".equalsIgnoreCase(role)) {
                        // Open teacher dashboard
                        teacherDash teacherDashboard = new teacherDash();
                        teacherDashboard.setVisible(true);
                    } else if ("STUDENT".equalsIgnoreCase(role)) {
                        // Open student dashboard
                        HomeDashboard homeDashboard = new HomeDashboard();
                        homeDashboard.setVisible(true);
                    } else {
                        // Unknown role, handle accordingly
                        JOptionPane.showMessageDialog(null, "Unknown role: " + role, "Role Error", JOptionPane.WARNING_MESSAGE);
                    
                        this.dispose();
                    }
                } else {
                    // Password incorrect
                    JOptionPane.showMessageDialog(null, "Login failed. Please check your email and password.", "Login Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // User not found
                JOptionPane.showMessageDialog(null, "Login failed. Please check your email and password.", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database error. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jBloginButinActionPerformed

    private void jTloginUserNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTloginUserNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTloginUserNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Window window = SwingUtilities.getWindowAncestor((JButton) evt.getSource());
    if (window != null) {
        window.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
}
    private void registerSelctAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSelctAdminActionPerformed
   // Assuming regisRoleEslectAdmin is a JComboBox
    // Assuming regisRoleEslectAdmin is a JComboBox
    String selectedRole = regisRoleEslectAdmin.getSelectedItem().toString();

    if ("Student".equalsIgnoreCase(selectedRole)) {
        // Open the SignUp form
        signUpStud signUpForm = new signUpStud();
        signUpForm.setVisible(true);
    } else if ("Teacher".equalsIgnoreCase(selectedRole)) {
        // Create a new JFrame to display the PasswordChangePanel
        JFrame passwordFrame = new JFrame("Password Change");
        passwordFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        passwordFrame.getContentPane().add(new PasswordChangePanel());
        passwordFrame.pack();
        passwordFrame.setLocationRelativeTo(null); // Center the frame on the screen
        passwordFrame.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a valid role.");
    }
          
    }//GEN-LAST:event_registerSelctAdminActionPerformed

    private void regisRoleEslectAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisRoleEslectAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regisRoleEslectAdminActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBloginButin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPloginUserN;
    private javax.swing.JTextField jTloginUserN;
    private javax.swing.JComboBox<String> regisRoleEslectAdmin;
    private javax.swing.JButton registerSelctAdmin;
    // End of variables declaration//GEN-END:variables
}
